spring.application.name=demo
jwt.secret=1F9A3C72D9E57B21C0F4A6FA13E22C78F4D9A11B7C1DA2E5F9A3C72D9E57B21
jwt.expiration=120
jwt.issuer=my-auth-server
login.role=ADMIN
login.username=admin
login.password=admin123